name: fusion_app
description: Mini Football Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  introduction_screen: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

  assets:
    - assets/icons/splash.png
    - assets/icons/o1.png
    - assets/icons/o2.png
    - assets/icons/o3.png
    - assets/icons/analog.png
    - assets/icons/altair.png
    - assets/icons/maqtaral.png
    - assets/icons/t1.png